local Notification_Main = Instance.new("ScreenGui")
local Notification_Layout_1 = Instance.new("Frame")
local Notification_Layout_2 = Instance.new("UIListLayout")
Notification_Main.Name = "Notification_Main"
Notification_Main.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")
Notification_Main.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
Notification_Main.DisplayOrder = 6000
Notification_Main.ResetOnSpawn = false
Notification_Layout_1.Name = "Notification_Layout_1"
Notification_Layout_1.Parent = Notification_Main
Notification_Layout_1.AnchorPoint = Vector2.new(1, 0.100000001)
Notification_Layout_1.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
Notification_Layout_1.BackgroundTransparency = 1.000
Notification_Layout_1.Position = UDim2.new(0.300000012, 0, 0.150000006, 0)
Notification_Layout_1.Size = UDim2.new(0, 280, 0, 700)
Notification_Layout_2.Name = "Notification_Layout_2"
Notification_Layout_2.Parent = Notification_Layout_1
Notification_Layout_2.SortOrder = Enum.SortOrder.LayoutOrder
Notification_Layout_2.Padding = UDim.new(0, 3)
